# Generated by Django 3.2.5 on 2021-07-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('spotifyToken', models.CharField(max_length=200, null=True)),
                ('appleToken', models.CharField(max_length=200, null=True)),
                ('authToken', models.CharField(max_length=200)),
                ('facebookToken', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True, auto_now=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userType', models.CharField(choices=[('Influencer', 'Influencer'), ('General', 'General'), ('SuperAdmin', 'SuperAdmin')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicalGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherContributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybackSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200, unique=True)),
                ('nodeId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmbot.album')),
                ('artist', models.ManyToManyField(to='fmbot.PlaybackSinger')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmbot.category')),
                ('genre', models.ManyToManyField(to='fmbot.MusicalGenre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmbot.language')),
                ('mix', models.ManyToManyField(to='fmbot.SongMix')),
                ('musicDirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmbot.musicdirector')),
                ('otherContributor', models.ManyToManyField(to='fmbot.OtherContributors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmbot.influence')),
            ],
        ),
        migrations.AddField(
            model_name='influence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmbot.mainuser'),
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotifyToken', models.CharField(max_length=200, null=True)),
                ('appleToken', models.CharField(max_length=200, null=True)),
                ('authToken', models.CharField(max_length=200)),
                ('facebookToken', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmbot.mainuser')),
            ],
        ),
    ]
