# Generated by Django 3.2.5 on 2021-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('songs', models.ManyToManyField(to='fmbot.Songs')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('songs', models.ManyToManyField(to='fmbot.Songs')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('artist', models.ManyToManyField(to='fmbot.PlaybackSinger')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('album', models.ManyToManyField(to='fmbot.Album')),
            ],
        ),
        migrations.CreateModel(
            name='NewReleases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('songs', models.ManyToManyField(to='fmbot.Songs')),
            ],
        ),
        migrations.CreateModel(
            name='ListenedToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('songs', models.ManyToManyField(to='fmbot.Songs')),
            ],
        ),
        migrations.CreateModel(
            name='ListenedThisWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('songs', models.ManyToManyField(to='fmbot.Songs')),
            ],
        ),
    ]
