# Generated by Django 3.2.5 on 2021-07-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmbot', '0005_auto_20210717_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='token',
            field=models.CharField(auto_created=True, default='abcd1234', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='tagToken',
            field=models.CharField(auto_created=True, default='abc123', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='KeyVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('key', models.CharField(max_length=1000, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmbot.influence')),
            ],
        ),
    ]
