# Generated by Django 3.2.5 on 2021-07-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmbot', '0002_listenedthisweek_listenedtoday_newreleases_trendingalbums_trendingartists_trendingmix_trendingsongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='username',
            field=models.CharField(default='guest', max_length=200, null=True),
        ),
    ]
