# Generated by Django 3.2.5 on 2021-08-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmbot', '0006_auto_20210717_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='password',
            field=models.CharField(default='False', max_length=100, null=True),
        ),
    ]
